package de.agiehl.bgprices.domain;

public enum FailureCode {
    NO_MATCH, EMPTY_NAME, BUNDLE_WITHOUT_ID, NO_PRICE_DATA, PARTIAL_RESULT,
    UPSTREAM_BLOCKED, UPSTREAM_HTTP_ERROR, NETWORK_ERROR, NAVIGATION_TIMEOUT,
    IDENTITY_MISMATCH, IDENTITY_UNCONFIRMED, NAME_CONFLICT, PARSER_ERROR, UNSAFE_NAVIGATION,
    BROWSER_CRASH, QUEUE_FULL, QUEUE_TIMEOUT, TOTAL_TIMEOUT, COOLDOWN, CACHE_UNAVAILABLE, SHUTTING_DOWN
}
